export const ACTIONS = {
  SET_USER_ID: 'SET_USER_ID',
  SET_USER_BASIC_DATA: 'SET_USER_BASIC_DATA',
  DISABLE_SHOW_QUOTE: 'DISABLE_SHOW_QUOTE',
  SET_USER_COMPLETED_ACTIVITIES: 'SET_USER_COMPLETED_ACTIVITIES',
  SET_USER_MOOD: 'SET_USER_MOOD',
  SET_DAILY_QUOTE: 'SET_DAILY_QUOTE',
  SET_USER_STORIES: 'SET_USER_STORIES',
  SET_PROGRESS_RANGE: 'SET_PROGRESS_RANGE',
  SET_IS_LOADING: 'SET_IS_LOADING',
};

export const setUser = data => {
  return {type: ACTIONS.SET_USER_ID, data};
};
